sudo: required
language: java
dist: trusty

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
    - env: JDK='OpenJDK 11'
      install: . ./install-jdk.sh -F 11 -L GPL
    - env: JDK='OpenJDK 12'
      install: . ./install-jdk.sh -F 12 -L GPL

addons:
  sonarcloud:
    organization: "artem-smotrakov-github"

script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=tlsbunny
